### ISSUE TITLE
Feature Request: Make Rssi attribute a sensor

### ISSUE THREAD

**Issue by Shredder5262** [zachcheatham/ha-omada#104]
In its current state the RSSI data is listed as an attribute within a device tracker entity and makes it unusable for things like a bar card to be able to recognize severity levels. I am requesting that the attribute be promoted to an individual sensor.

**Comment by Shredder5262** [comment]
Also, quick sidenote, the integration in HA states it's 0.4.0-beta1, but the latest installed version is 5.0, not sure if those should be different, but if they should be that makes it confusing to verify correct version numbers...what is 'truth' in this case?
![2024-05-10 21_18_27-Settings – Home Assistant - Vivaldi](https://github.com/zachcheatham/ha-omada/assets/59770346/e7f0f1b9-0f73-4649-aa95-4bb9e77620e6)
![2024-05-10 21_20_55-Release 0 5 0 · zachcheatham_ha-omada - Vivaldi](https://github.com/zachcheatham/ha-omada/assets/59770346/1610618d-d593-4998-8064-be40d23914d0)

I do think this is a really good integration for omada, but does need some adjustments.

**Comment by zachcheatham** [comment]
This change has been added in the latest pre-release.

**Comment by bruin14** [comment]
Some people were using the 'signal_level' and ap_name attribute to track in which room someone is from a list of phones in the home. I guess it has been removed?  The above problem could have been easily fixed with a template helper. Now there is no link anymore between the device entity and the signal strength entity
