### ISSUE TITLE
Exception in async_update when dispatching...

### ISSUE THREAD

**Issue by spry-salt** [zachcheatham/ha-omada#111]
I'm seeing these messages fairly frequently. I've deleted and reinstalled ha-omada using HACS. 

Currently using HA core 2024.9.2 and TP-Link Omada v0.6.0-beta.1.

`Event name: homeassistant.util.logging Event message: Exception in async_update when dispatching 'omada-update-somelongstringhere': () Traceback (most recent call last): File "/config/custom_components/omada/sensor.py", line 911, in async_update await super().async_update() File "/config/custom_components/omada/omada_controller_entity.py", line 79, in async_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state self.__async_calculate_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state if extra_state_attributes := self.extra_state_attributes: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/omada/sensor.py", line 904, in extra_state_attributes return self.entity_description.extra_attributes_fn(self.controller) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/omada/sensor.py", line 71, in controller_clients_extra_attributes_fn attributes["clients"] = sorted(clients, key=lambda x: ipaddress.IPv4Address(x["ip"])) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/omada/sensor.py", line 71, in attributes["clients"] = sorted(clients, key=lambda x: ipaddress.IPv4Address(x["ip"])) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/ipaddress.py", line 1319, in __init__ self._ip = self._ip_int_from_string(addr_str) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/ipaddress.py", line 1206, in _ip_int_from_string raise AddressValueError("Expected 4 octets in %r" % ip_str) ipaddress.AddressValueError: Expected 4 octets in 'None'`

**Comment by zachcheatham** [comment]
Was this happening in the latest stable Omada controller?

**Comment by spry-salt** [comment]
Hmm, I’m not sure to be honest.

**Comment by h3llrais3r** [comment]
Having the same issue:
![image](https://github.com/user-attachments/assets/93e4f210-8220-44a3-879f-46810d08f677)

@zachcheatham 
Seems that not all clients have an ipv4 address assigned to it in `x["ip"]`?

It probably happens since my PR for the connected client details, but at the time this was tested, I always got an ip address for every client: https://github.com/zachcheatham/ha-omada/pull/102/files#diff-68b01b3b2c5af283396c6686144967aa7f005f5c271c841dcfc1369d11bd630eR67

Not sure how it's possible that omada returns a client with an ip address = `None`?

Maybe we can fix it by ignoring `None` values in the sorting by checking if an ip is present and replace it with a default value (like "0.0.0.0")?
Going to make this change on my local system and see if this error still happens.

PS: can we only have ipv4 addresses here or also ipv6?
If also ipv6, we can replace `ipaddress.IPv4Address(...)` by `ipaddress.ip_address(...)` to support both.

So we could use something like this:
```python
attributes["clients"] = sorted(clients, key=lambda x: ipaddress.ip_address(x["ip"] if x["ip"] else "0.0.0.0"))
```

**Comment by h3llrais3r** [comment]
Running my PR for a day now, and haven't seen the error anymore since then.
Going to check in the coming days as well, as I can't figure out how we can have a client without an ip assigned to it.

**Comment by h3llrais3r** [comment]
Still haven't seen the error anymore since running I'm running my PR. 😉

**Comment by h3llrais3r** [comment]
@zachcheatham Please review and accept my PR https://github.com/zachcheatham/ha-omada/pull/112 as it fixes this issue.
Have been running it for more than a month now, and I haven't seen this issue anymore at all.

**Comment by zachcheatham** [comment]
Fix has been merged. Apologies for the delay!

**Comment by h3llrais3r** [comment]
No problem, thanks for merging it. 👍
